# 

# WEEK 11

In [1]:
import numpy as np
import pandas as pd

### STACK, SPLIT, RESIZE

In [53]:
x = np.array([[1,2,3],[5,6,7]])
y = np.array([2,3,4])
z = np.array([7,8,9])
xy = np.vstack((x,y,z)) #Gabungin secara vertikal
print(xy)

[[1 2 3]
 [5 6 7]
 [2 3 4]
 [7 8 9]]


In [54]:
a = np.array([[10],[11],[12],[13]])
A = np.hstack((xy,a)) #menggabungkan secara horizontal
A

array([[ 1,  2,  3, 10],
       [ 5,  6,  7, 11],
       [ 2,  3,  4, 12],
       [ 7,  8,  9, 13]])

In [57]:
b = np.hsplit(A, 2) #membagi matrix A menjadi 2
b

[array([[1, 2],
        [5, 6],
        [2, 3],
        [7, 8]]),
 array([[ 3, 10],
        [ 7, 11],
        [ 4, 12],
        [ 9, 13]])]

In [58]:
c = np.vsplit(A,2)
c

[array([[ 1,  2,  3, 10],
        [ 5,  6,  7, 11]]),
 array([[ 2,  3,  4, 12],
        [ 7,  8,  9, 13]])]

In [61]:
np.resize(A, (4,5))

array([[ 1,  2,  3, 10,  5],
       [ 6,  7, 11,  2,  3],
       [ 4, 12,  7,  8,  9],
       [13,  1,  2,  3, 10]])

In [7]:
np.resize(A, (2,2))

array([[ 1,  2],
       [ 3, 10]])

### DIAGONAL

In [62]:
A

array([[ 1,  2,  3, 10],
       [ 5,  6,  7, 11],
       [ 2,  3,  4, 12],
       [ 7,  8,  9, 13]])

In [63]:
diag1 = np.diag(A)
diag1

array([ 1,  6,  4, 13])

In [65]:
np.diag(np.flip(A)) #membalikkan diagonal
np.flip(A)

array([[13,  9,  8,  7],
       [12,  4,  3,  2],
       [11,  7,  6,  5],
       [10,  3,  2,  1]])

In [11]:
np.fliplr(A) #reverse order (bisa mengambil bukan diagonal utama)

array([[10,  3,  2,  1],
       [11,  7,  6,  5],
       [12,  4,  3,  2],
       [13,  9,  8,  7]])

In [12]:
np.flip(A)

array([[13,  9,  8,  7],
       [12,  4,  3,  2],
       [11,  7,  6,  5],
       [10,  3,  2,  1]])

In [13]:
diag2 = np.diag(np.fliplr(A)) # reverse the order of array
diag2

array([10,  7,  3,  7])

### select value other than diagonal

In [14]:
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
A

array([[ 1,  2,  3, 10],
       [ 5,  6,  7, 11],
       [ 2,  3,  4, 12],
       [ 7,  8,  9, 13]])

In [16]:
rows, col = matrix.shape

In [17]:
desired_elements = []
for i in range(rows):
    for j in range(col):
        if i != j and i != (rows - 1 - j):
            desired_elements.append(matrix[i][j])

print(desired_elements)

[1, 3, 5, 7]


## MATRIX OPERATION

In [66]:
mtx1 = np.arange(1,10).reshape((3,3))
mtx1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
mtx2 = np.arange(21,30).reshape((3,3))
mtx2

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [20]:
jumlah  = mtx1 + mtx2
jumlah

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [21]:
kurang = mtx1 - mtx2;kurang

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [22]:
skalar = mtx1 * mtx2;skalar #np.out

array([[ 21,  44,  69],
       [ 96, 125, 156],
       [189, 224, 261]])

In [23]:
perkalian = mtx1 @ mtx2;perkalian #perkalian matrix %*% kalo di R

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [24]:
perkalian2 = np.dot(mtx1, mtx2);perkalian2

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [25]:
np.transpose(perkalian) #T

array([[150, 366, 582],
       [156, 381, 606],
       [162, 396, 630]])

In [26]:
np.transpose(A)

array([[ 1,  5,  2,  7],
       [ 2,  6,  3,  8],
       [ 3,  7,  4,  9],
       [10, 11, 12, 13]])

In [27]:
eigenvalue, eigenvector = np.linalg.eig(A) #LINEAR ALGEBRA

In [28]:
eigenvalue

array([ 2.84530518e+01, -4.28917108e+00,  7.55495248e-16, -1.63880686e-01])

In [29]:
eigenvector

array([[ 3.25929620e-01,  6.17189934e-01,  4.08248290e-01,
        -7.19998633e-02],
       [ 5.27971978e-01, -2.11673977e-01, -8.16496581e-01,
        -6.40793482e-01],
       [ 4.17279297e-01,  5.99238596e-01,  4.08248290e-01,
         7.58878121e-01],
       [ 6.63998089e-01, -4.63879098e-01,  8.08038207e-17,
        -9.11248148e-02]])

In [30]:
det = np.linalg.det(A);det 

7.99360577730114e-15

In [31]:
det1 = np.linalg.det(mtx1);det1

0.0

In [32]:
inv = np.linalg.inv(A);inv

array([[ 1.00079992e+15, -1.12589991e+15, -7.50599938e+14,
         8.75699928e+14],
       [-2.00159983e+15,  2.25179981e+15,  1.50119988e+15,
        -1.75139986e+15],
       [ 1.00079992e+15, -1.12589991e+15, -7.50599938e+14,
         8.75699928e+14],
       [-5.55555556e-01,  0.00000000e+00,  6.66666667e-01,
        -1.11111111e-01]])

### Membangkitkan data 

### Distribusi Normal X~(0,1)

In [33]:
seed_value = 100 
np.random.seed(seed_value)
mean = 0
std_dev = 1
X1 = np.random.normal(0, 1, size=50)
print(X1)

[-1.74976547  0.3426804   1.1530358  -0.25243604  0.98132079  0.51421884
  0.22117967 -1.07004333 -0.18949583  0.25500144 -0.45802699  0.43516349
 -0.58359505  0.81684707  0.67272081 -0.10441114 -0.53128038  1.02973269
 -0.43813562 -1.11831825  1.61898166  1.54160517 -0.25187914 -0.84243574
  0.18451869  0.9370822   0.73100034  1.36155613 -0.32623806  0.05567601
  0.22239961 -1.443217   -0.75635231  0.81645401  0.75044476 -0.45594693
  1.18962227 -1.69061683 -1.35639905 -1.23243451 -0.54443916 -0.66817174
  0.00731456 -0.61293874  1.29974807 -1.73309562 -0.9833101   0.35750775
 -1.6135785   1.47071387]


### Distribusi Binomial X~(n,p)

In [34]:
seed_value = 100 
np.random.seed(seed_value)
n_trials = 10
prob_success = 0.5
X2 = np.random.binomial(n_trials, prob_success, size=50)
print(X2)

[5 4 5 7 1 3 6 6 3 5 7 4 4 3 4 8 6 4 6 4 5 7 6 4 4 4 1 4 6 2 5 5 3 5 2 7 8
 3 7 5 6 6 5 2 4 5 6 4 4 7]


### Distribusi Poisson X~(λ)

In [35]:
seed_value = 100 
np.random.seed(seed_value)
lamda = 5
X3 = np.random.poisson(lamda, size=50)
print(X3)

[4 4 3 5 6 2 4 8 4 7 2 7 3 6 5 6 4 7 5 5 6 5 3 2 6 6 6 4 7 5 6 6 9 5 5 7 7
 4 2 1 3 7 9 7 6 5 5 2 6 2]


### Distribusi Eksponensial X~(θ)

*θ = 1/λ

In [36]:
seed_value = 100 
np.random.seed(seed_value)
lamda = 5
X4 = np.random.exponential(1/lamda, size=50)
print(X4)

[0.15679167 0.06524838 0.11050932 0.37257738 0.00094601 0.02592361
 0.22218703 0.34957082 0.02940013 0.17117715 0.4438731  0.04694257
 0.04099399 0.02294235 0.04961472 0.76909528 0.33392587 0.03773418
 0.33880835 0.06406137 0.11302264 0.56278157 0.34036479 0.08192835
 0.03857391 0.09330818 0.00114095 0.05818449 0.31759646 0.00307451
 0.18268067 0.18516952 0.02221932 0.09623506 0.00743159 0.44220468
 0.79183191 0.01236274 0.44245008 0.17203005 0.27133134 0.1989499
 0.17437928 0.00413018 0.0471512  0.1573531  0.29316725 0.05772189
 0.06734525 0.38264322]


### Distribusi Chi Square X~(v)

In [37]:
seed_value = 100 
np.random.seed(seed_value)
df_chi_square = 3
X5 = np.random.chisquare(df_chi_square, size=50)
print(X5)

[ 0.22713311  3.15465388  5.16002976  3.62977841  1.94744802  2.92868706
  1.4771514   3.40529007  4.10915697  2.11496921  1.50905952  0.65533138
  7.8691517   7.49919909  2.7550682   4.99950968  1.69715155  2.45568565
  1.05113156  4.57879767  5.96213553  0.25525881  1.34375238  1.16709534
  6.41792119  0.23483893  0.29524925  7.17059906  0.83475682  0.96285593
  2.57649462  3.61122154  2.16554408  0.89073922  2.88577254  2.36272409
  3.92399312  4.31241507  0.18785186  3.21689946 10.06595009  1.33439075
  3.82564571  0.66819529  0.3215232   4.88511411  2.57651429  2.39496783
  1.29298666  0.58300226]


### 

### Distribusi Gamma X~(α,β)


In [38]:
seed_value = 100 
np.random.seed(seed_value)
alpha_gamma = 2
beta_gamma = 2
X6 = np.random.gamma(alpha_gamma, beta_gamma, size=50)
print(X6)

[ 0.54919369  4.29872583  6.56330828  4.84512299  2.86760589  4.03604614
  2.28505854  4.58789371  5.3894613   3.0709474   2.32522146  1.19935646
  9.50440952  9.10831898  3.83281711  6.38549899  2.55995221  3.47916463
  1.73699286  5.91703411  7.44499047  0.59638255  2.11594725  1.88864082
  7.94148363  0.56223104  0.66179582  8.75522643  1.44760522  1.62003934
  3.62239246  4.82391932  3.13197433  1.52339182  3.98593089  3.36843805
  5.17995659  5.61843399  0.48126197  4.37074673 11.82968273  2.10400231
  5.06830578  1.2174657   0.70386098  6.2584775   3.62241572  3.40689597
  2.05104385  1.09647337]


### Distribusi Beta X~(α,β)

In [39]:
seed_value = 100 
np.random.seed(seed_value)
alpha_beta = 2
beta_beta = 2
X7 = np.random.beta(alpha_beta, beta_beta, size=50)
print(X7)

[0.11328441 0.57530331 0.41537521 0.33247118 0.63702139 0.65971629
 0.51064031 0.37509283 0.42389513 0.22693843 0.92583573 0.52838075
 0.93388407 0.07027655 0.4718947  0.42887269 0.67276649 0.54198136
 0.47969709 0.09918819 0.84899886 0.80631404 0.10109548 0.51533007
 0.65163864 0.81644441 0.48437081 0.33216526 0.54275302 0.52091422
 0.70771405 0.67900666 0.63081699 0.05763815 0.76681611 0.52151492
 0.55146391 0.267458   0.17340856 0.55317547 0.71307264 0.25734015
 0.82180103 0.68908266 0.71696224 0.60979509 0.89513601 0.3639005
 0.87408494 0.56004476]


### 

### Menggabungkan Semua Data

In [40]:
pip install pandas openpyxl

Note: you may need to restart the kernel to use updated packages.


### Eksport Data

In [41]:
DataX = pd.DataFrame({'X1': X1, 'X2': X2, 'X3': X3, 'X4': X4, 'X5': X5, 'X6': X6, 'X7': X7})
print(DataX)
DataX.to_excel('DataX.xlsx', index=False)

          X1  X2  X3        X4         X5         X6        X7
0  -1.749765   5   4  0.156792   0.227133   0.549194  0.113284
1   0.342680   4   4  0.065248   3.154654   4.298726  0.575303
2   1.153036   5   3  0.110509   5.160030   6.563308  0.415375
3  -0.252436   7   5  0.372577   3.629778   4.845123  0.332471
4   0.981321   1   6  0.000946   1.947448   2.867606  0.637021
5   0.514219   3   2  0.025924   2.928687   4.036046  0.659716
6   0.221180   6   4  0.222187   1.477151   2.285059  0.510640
7  -1.070043   6   8  0.349571   3.405290   4.587894  0.375093
8  -0.189496   3   4  0.029400   4.109157   5.389461  0.423895
9   0.255001   5   7  0.171177   2.114969   3.070947  0.226938
10 -0.458027   7   2  0.443873   1.509060   2.325221  0.925836
11  0.435163   4   7  0.046943   0.655331   1.199356  0.528381
12 -0.583595   4   3  0.040994   7.869152   9.504410  0.933884
13  0.816847   3   6  0.022942   7.499199   9.108319  0.070277
14  0.672721   4   5  0.049615   2.755068   3.832817  0

### Import Data

In [42]:
DataX = pd.read_excel('DataX.xlsx')
print(DataX)

          X1  X2  X3        X4         X5         X6        X7
0  -1.749765   5   4  0.156792   0.227133   0.549194  0.113284
1   0.342680   4   4  0.065248   3.154654   4.298726  0.575303
2   1.153036   5   3  0.110509   5.160030   6.563308  0.415375
3  -0.252436   7   5  0.372577   3.629778   4.845123  0.332471
4   0.981321   1   6  0.000946   1.947448   2.867606  0.637021
5   0.514219   3   2  0.025924   2.928687   4.036046  0.659716
6   0.221180   6   4  0.222187   1.477151   2.285059  0.510640
7  -1.070043   6   8  0.349571   3.405290   4.587894  0.375093
8  -0.189496   3   4  0.029400   4.109157   5.389461  0.423895
9   0.255001   5   7  0.171177   2.114969   3.070947  0.226938
10 -0.458027   7   2  0.443873   1.509060   2.325221  0.925836
11  0.435163   4   7  0.046943   0.655331   1.199356  0.528381
12 -0.583595   4   3  0.040994   7.869152   9.504410  0.933884
13  0.816847   3   6  0.022942   7.499199   9.108319  0.070277
14  0.672721   4   5  0.049615   2.755068   3.832817  0

## Statistika Deskriptif

### Rata-rata Sampel

In [44]:
def rata_rata(data):
    rata = {}
    for column in data.columns:
        rata[column] = sum(data[column]) / len(data[column])
    return rata

ratarata = rata_rata(DataX)
print("Rata Rata ")
for key, value in ratarata.items():
    print(f"{key}: {value}")

Rata Rata 
X1: -0.040800707873950154
X2: 4.74
X3: 5.02
X4: 0.18542174698495453
X5: 2.8390158580627247
X6: 3.820830854473588
X7: 0.5290554753855634


### Varians Sampel

In [45]:
def hitung_varians(data):
    varians ={}
    for column in data.columns :
        rata = sum(data[column]) / len(data[column])
        varians[column] = sum((data[column]-rata)**2)/(len(data[column])-1)
    return varians

varian_sampel = hitung_varians(DataX)
print("Varians sampel tiap variabel ")
for key, value in varian_sampel.items():
    print(f"{key}: {value}")

Varians sampel tiap variabel 
X1: 0.9039746746712508
X2: 2.849387755102041
X3: 3.6118367346938784
X4: 0.03659832781086262
X5: 5.140586469401251
X6: 6.955106327407805
X7: 0.05546411256971485


### Korelasi

In [46]:
import pandas as pd

def korelasi(data):
    korel = {}
    for col1 in data.columns:
        for col2 in data.columns:
            if col1 != col2:
                mean_col1 = sum(data[col1]) / len(data[col1])
                mean_col2 = sum(data[col2]) / len(data[col2])
                covar = sum((data[col1] - mean_col1) * (data[col2] - mean_col2)) / (len(data) - 1)
                std_dev_col1 = (sum((data[col1] - mean_col1) ** 2) / (len(data) - 1)) ** 0.5
                std_dev_col2 = (sum((data[col2] - mean_col2) ** 2) / (len(data) - 1)) ** 0.5
                korel[(col1, col2)] = covar / (std_dev_col1 * std_dev_col2)
    
    # Membuat matriks korelasi
    matriks_korelasi = pd.DataFrame(index=data.columns, columns=data.columns)
    for col1 in matriks_korelasi.columns:
        for col2 in matriks_korelasi.columns:
            if col1 == col2:
                matriks_korelasi.loc[col1, col2] = 1.0
            else:
                matriks_korelasi.loc[col1, col2] = korel[(col1, col2)]

    return matriks_korelasi

matrikskorelasi = korelasi(DataX)

print("Matriks Korelasi:")
print( matrikskorelasi)



Matriks Korelasi:
          X1        X2        X3        X4        X5        X6        X7
X1       1.0 -0.103875  0.087194 -0.033482  0.007117  0.001127  0.112321
X2 -0.103875       1.0 -0.100131  0.886369  -0.00267 -0.002818  -0.04805
X3  0.087194 -0.100131       1.0 -0.011453 -0.071069 -0.063595  0.091705
X4 -0.033482  0.886369 -0.011453       1.0 -0.069421 -0.069486 -0.000853
X5  0.007117  -0.00267 -0.071069 -0.069421       1.0  0.998866  0.042302
X6  0.001127 -0.002818 -0.063595 -0.069486  0.998866       1.0  0.042252
X7  0.112321  -0.04805  0.091705 -0.000853  0.042302  0.042252       1.0


## MAX MIN SORT MEDIAN

### Max Min

In [ ]:
data = pd.read_excel('max_min.xlsx')
data

In [ ]:
def findmax(input):
    max_value = input[0]
    for value in input:
        if value > max_value:
            max_value = value
    return max_value

In [ ]:
findmax(data['Value'])

In [ ]:
def findmin(input):
    min_value = input[0]
    for value in input:
        if value < min_value:
            min_value = value
    return min_value

In [ ]:
findmin(data['Value'])

In [ ]:
data['Value'].max()

In [ ]:
data['Value'].min()

In [ ]:
len(data['Value'])

### Sorting

In [ ]:
def sorting(input):
    n = len(input)
    for i in range(n-1):
        for j in range(n - i - 1):
            if input[j] > input[j+1]:
                input[j], input[j+1] = input[j+1], input[j]

In [ ]:
sorting(data['Value'])
data['Value']

In [ ]:
data2 = [[10, 18, 11], [13, 15, 8], [9, 20, 3]]
df = pd.DataFrame(data2)
df

In [ ]:
df = df.set_axis(["x1","x2","x3"], axis = 1)
df

In [ ]:
df = df.set_axis(['y1','y2','y3'], axis = 0)
df

In [ ]:
df.max()

### Sorting, max, min, median data simultan

- Asceding (pengurutan data dari yang terkecil ke yang terbesar) elemen terkecil berada di indeks 0, dan elemen terbesar berada di indeks -1.

-  Desceding (pengurutan data dari yang terbesar ke yang terkecil) elemen terkecil berada di indeks -1, dan elemen terbesar berada di indeks 0.

- Median Genap : Me = [data ke (n ÷ 2) + data ke (n ÷ 2) + 1] ÷ 2

- Median Ganjil : Me = data ke (n + 1) ÷ 2

In [49]:
def sortmanual(data):
    sorted_data = {}
    for column in data.columns:
        data_list = list(data[column])
        n = len(data_list)

        for i in range(n - 1):
            for j in range(0, n - i - 1):
                if data_list[j] > data_list[j + 1]:
                    data_list[j], data_list[j + 1] = data_list[j + 1], data_list[j]

        sorted_data[column] = data_list

    return sorted_data

hasilsortmanual = sortmanual(DataX)
print("Hasil sorting manual:")
for key, value in hasilsortmanual.items():
    print(f"{key}: {value}", "\n")

Hasil sorting manual:
X1: [-1.749765473054697, -1.733095623653281, -1.690616826383604, -1.613578502822176, -1.443216995225337, -1.356399048861313, -1.232434513914926, -1.118318246255436, -1.070043330568293, -0.98331009912963, -0.8424357382512976, -0.7563523055944354, -0.6681717368134277, -0.6129387354781626, -0.5835950503226648, -0.5444391616724643, -0.5312803768519098, -0.4580269855026243, -0.4559469274680022, -0.4381356227044174, -0.3262380592023025, -0.2524360365213899, -0.251879139213213, -0.1894958308231753, -0.1044111433906277, 0.007314563228903049, 0.0556760148547769, 0.1845186905639428, 0.2211796692214004, 0.2223996085553049, 0.2550014442733817, 0.3426804033275022, 0.3575077531673654, 0.4351634881228921, 0.5142188413943821, 0.672720805709661, 0.7310003438348087, 0.7504447615341785, 0.8164540110192858, 0.816847071685779, 0.9370822011089522, 0.9813207869512316, 1.029732685133346, 1.153035802563644, 1.189622268029126, 1.299748074755309, 1.361556125145331, 1.470713866612129, 1.5416

In [50]:

# Maksimum dan Minimum
for column in hasilsortmanual:
    min_value = hasilsortmanual[column][0]
    max_value = hasilsortmanual[column][-1]

# Median
    n = len(hasilsortmanual[column])
    if n % 2 == 0:
        median_value = (hasilsortmanual[column][n // 2 + 1] + hasilsortmanual[column][n // 2]) / 2
    else:
        median_value = hasilsortmanual[column][n // 2 + 1]

    print(f"\n{column}")
    print(f"Nilai Minimum: {min_value}")
    print(f"Nilai Maksimum: {max_value}")
    print(f"Median: {median_value}")


X1
Nilai Minimum: -1.749765473054697
Nilai Maksimum: 1.61898166067526
Median: 0.03149528904183997

X2
Nilai Minimum: 1
Nilai Maksimum: 8
Median: 5.0

X3
Nilai Minimum: 1
Nilai Maksimum: 9
Median: 5.0

X4
Nilai Minimum: 0.000946005028630547
Nilai Maksimum: 0.7918319061517197
Median: 0.13490715603871006

X5
Nilai Minimum: 0.1878518648223113
Nilai Maksimum: 10.06595009005588
Median: 2.5160901353846628

X6
Nilai Minimum: 0.4812619738433839
Nilai Maksimum: 11.82968272530328
Median: 3.550778547781276

X7
Nilai Minimum: 0.05763815051680954
Nilai Maksimum: 0.9338840659241113
Median: 0.5471084655693484


In [63]:
sorted_data = DataX.sort_values(by=list(DataX.columns))
print(sorted_data)

          X1  X2  X3        X4         X5         X6        X7
0  -1.749765   5   4  0.156792   0.227133   0.549194  0.113284
45 -1.733096   5   5  0.157353   4.885114   6.258477  0.609795
37 -1.690617   3   4  0.012363   4.312415   5.618434  0.267458
48 -1.613579   4   6  0.067345   1.292987   2.051044  0.874085
31 -1.443217   5   6  0.185170   3.611222   4.823919  0.679007
38 -1.356399   7   2  0.442450   0.187852   0.481262  0.173409
39 -1.232435   5   1  0.172030   3.216899   4.370747  0.553175
19 -1.118318   4   5  0.064061   4.578798   5.917034  0.099188
7  -1.070043   6   8  0.349571   3.405290   4.587894  0.375093
46 -0.983310   6   5  0.293167   2.576514   3.622416  0.895136
23 -0.842436   4   2  0.081928   1.167095   1.888641  0.515330
32 -0.756352   3   9  0.022219   2.165544   3.131974  0.630817
41 -0.668172   6   7  0.198950   1.334391   2.104002  0.257340
43 -0.612939   2   7  0.004130   0.668195   1.217466  0.689083
12 -0.583595   4   3  0.040994   7.869152   9.504410  0

### Median 

Genap : Me = [data ke (n ÷ 2) + data ke (n ÷ 2) + 1] ÷ 2

Ganjil : Me = data ke (n + 1) ÷ 2

In [52]:
def nilaimedian(data):
     mediandata= {}
     for column in data.columns:
        urutkandata = sorted(data[column])
        n = len(urutkandata)
        if n % 2 == 0:
            median = (urutkandata[n // 2] + urutkandata[(n // 2)+1]) / 2
        else:
            median = urutkandata[(n // 2)+1]
        mediandata[column] = median
     return mediandata
hasilmedian = nilaimedian(DataX)

print("Median:")
for key, value in hasilmedian.items():
    print(f"{key}: {value}", "\n")

Median:
X1: 0.03149528904183997 

X2: 5.0 

X3: 5.0 

X4: 0.13490715603871006 

X5: 2.5160901353846628 

X6: 3.550778547781276 

X7: 0.5471084655693484 



<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=235be482-bea5-41e0-a131-c60cdaf79d4f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>