# Komstat W9

introduction to python

# Basic Python Command

## Variables

In [1]:
print('hello world')

hello world


* **str()** -> convert a value (oftern numeric) to a **string** data type
* **int()** -> convert a value (usually float) to an **integer** data type
* **float()** -> convert a value (usually an integer) to a **float** data type

In [5]:
hotel_room = 100
tax = hotel_room * 0.08
total = hotel_room + tax
room_guests = 5
share_per_person = total/room_guests

print(share_per_person)
print("Each person needs to pay: "+str(share_per_person))

21.6
Each person needs to pay: 21.6


In [6]:
salutation = 'Dr.'
first_name = 'Prisha'
middle_name = 'Jai'
last_name = 'Agarwal'
suffix = 'Ph.D.'

print(salutation + ' ' + first_name + ' ' + middle_name + ' ' + last_name + ' ' + suffix)

Dr. Prisha Jai Agarwal Ph.D.


In [3]:
print('5 * 3 = ' + str(5*3))


5 * 3 = 15


## Conditionals

Comparison with numerical values
* x == y 
* x != y
* x < y
* x <= y
* x > y
* x >= y

Comparison with strings
* “x” == “y” -> if kata-katanya sama, return True. Jika tidak, kembalikan nilai false
* “x” != “y” -> jika kata-katanya **tidak** sama, return True. Jika tidak, kembalikan false
* “x” < “y” -> jika string “x” memiliki nilai Unicode yang lebih kecil dari string “y”, kembalikan True
* “x” <= “y” -> jika string “x” memiliki nilai Unicode yang lebih kecil atau sama dengan string “y”, kembalikan True
* “x” > “y” -> jika string “x” memiliki nilai Unicode yang lebih besar dari string “y”, kembalikan True
* “x” >= “y” -> jika string “x” memiliki nilai yang lebih besar atau sama dengan string “y”, return ersion)



In [7]:
print("tall" < "short")

print(chr(116)+chr(97)+chr(108)+chr(108))

print('aab' < 'aac')

ord('A')

False
tall
True


65

In [11]:
# basic if-elif-else 

x = 3
if x == 0:
    print('zero number')
elif x < 0:
    print('negative number')
else:
    print('positive number')

positive number


## Functions

In [16]:
def find_total_days(years, months, days):
    
    my_days = (years*365) + (months*30) + days
    mydays2 = my_days+10
    return my_days, mydays2

print(find_total_days(2,6,28))

(938, 948)


In [25]:
def convert_volume(fluid_ounce):
    ml = fluid_ounce * 29.5
    # m11 = fluid_ounce * 35
    return ml

print("The volume in millimeters is " + str(convert_volume(2)))
print("The volume in millimeters is " + str(convert_volume(2)*2))

The volume in millimeters is 59.0
The volume in millimeters is 118.0


# Packages in Python

In [10]:
# cara install
# pip install nama_packages
pip install pandas
pip install numpy
 #pip install matplotlib
# pip install seaborn

SyntaxError: invalid syntax (3996000999.py, line 3)

cara manggil packages
import **nama packages** as **singkatan**

biasa packages ada singkatan nya sendiri

* numpy -> np 
* pandas -> pd 
* tensorflow -> tf 
* matplotlib.pyplot -> plt 
* seaborn -> sns 

In [27]:
import pandas as pd
import numpy as np

# Numpy
https://numpy.org/doc/stable/reference/routines.html

In [28]:
x=1.34
a = [1.2,2.3,3.4,4.5,5.6]
#Rounding
print(round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))
print(np.around(a))
#membuat array
b = np.array (a)
print (b)
#Sum, Product, Differences
print(sum(b))
print(np.prod(b))
print(np.diff(b))

1
1.0
2.0
1.0
[1. 2. 3. 4. 6.]
[1.2 2.3 3.4 4.5 5.6]
17.0
236.47679999999994
[1.1 1.1 1.1 1.1]


In [31]:
# c = [1,2,3,4,5]
# c.type

AttributeError: 'list' object has no attribute 'type'

In [30]:
print(b.shape)
print(b.dtype)


(5,)
float64


In [31]:
a = np.array([1,2,3,4,5,6,7,8,9,10],ndmin=2,dtype=complex)
print(a)
print(a.shape) #1 row 10 column
print(a.dtype)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
  10.+0.j]]
(1, 10)
complex128


In [32]:
a = np.array([[1,2,3],[4,5,6]]) #2dimenion
print (a)
a.shape #2 row 3 column
a.shape = (3,2)
print(a)
print('\n')
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #2dimention
print (c)
print(np.asmatrix(c))
print(c.shape) #4 rows 3 columns
d = np.asmatrix(c)
print(type(d))
print(type(c))
print(type(a))
c[2,1] #baris 3 kolom 2

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
<class 'numpy.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


8

In [33]:
a = np.array([[1,2,3], [4,5,6]])
b = np.swapaxes(a,1,0)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [17]:
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #2dimention
print (d)
print(d.shape) #2 manages 2 rows 3 columns 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


# Pandas
https://pandas.pydata.org/docs/reference/index.html


In [37]:
data = pd.read_csv("C:/Users/Nazia Mahmudah/Downloads/SEMESTER 5/NGASDOS KOMSTAT 2023/train_features_complete.csv")
data.head()

waktu_setempat   id_jalan  id_titik_mulai  id_titik_akhir  \
0  2020-02-01 01:00:00+00:00  691007296        21390008      1425033102   
1  2020-02-01 01:00:00+00:00   47010584      1677092762       579493410   
2  2020-02-01 01:00:00+00:00   22932408        26486694      1930267566   
3  2020-02-01 01:00:00+00:00  142479648      1111592522      3775231113   
4  2020-02-01 01:00:00+00:00    8504977      5940503398      5940503394   

   rerata_kecepatan    highway  lit maxspeed                name    ref  
0            29.126      trunk  yes   30 mph  Upper Tooting Road    A24  
1            46.576    primary  yes   30 mph           High Road  A1000  
2            36.587  secondary  yes   20 mph    Nightingale Lane   B237  
3            34.063    primary  yes   20 mph       Lavender Hill  A3036  
4            38.336    primary  yes   30 mph         Harrow Road   A404

In [38]:
df = data.copy()
df = df.drop(columns = ['highway','lit','maxspeed','name','ref'], axis = 1)
df.head()

waktu_setempat   id_jalan  id_titik_mulai  id_titik_akhir  \
0  2020-02-01 01:00:00+00:00  691007296        21390008      1425033102   
1  2020-02-01 01:00:00+00:00   47010584      1677092762       579493410   
2  2020-02-01 01:00:00+00:00   22932408        26486694      1930267566   
3  2020-02-01 01:00:00+00:00  142479648      1111592522      3775231113   
4  2020-02-01 01:00:00+00:00    8504977      5940503398      5940503394   

   rerata_kecepatan  
0            29.126  
1            46.576  
2            36.587  
3            34.063  
4            38.336

In [41]:
df['id_jalan'].describe()

count    3.986480e+05
mean     8.017984e+07
std      1.561702e+08
min      1.210000e+03
25%      4.060819e+06
50%      2.470429e+07
75%      6.692459e+07
max      6.910073e+08
Name: id_jalan, dtype: float64

In [42]:
df.to_csv('df.csv', index = False)

In [43]:
pd.read_csv('df.csv')

waktu_setempat   id_jalan  id_titik_mulai  id_titik_akhir  \
0       2020-02-01 01:00:00+00:00  691007296        21390008      1425033102   
1       2020-02-01 01:00:00+00:00   47010584      1677092762       579493410   
2       2020-02-01 01:00:00+00:00   22932408        26486694      1930267566   
3       2020-02-01 01:00:00+00:00  142479648      1111592522      3775231113   
4       2020-02-01 01:00:00+00:00    8504977      5940503398      5940503394   
...                           ...        ...             ...             ...   
398643  2020-02-22 23:00:00+00:00    3691841        18235127      1590448416   
398644  2020-02-22 23:00:00+00:00    3691841      1250564256        18293380   
398645  2020-02-22 23:00:00+00:00  182210371        33139383        33139375   
398646  2020-02-22 23:00:00+00:00    8504977      1623682036        26467191   
398647  2020-02-22 23:00:00+00:00  150783571       290025573       873734149   

        rerata_kecepatan  
0                 29.126  
1                 46.576  
2                 36.587  
3                 34.063  
4                 38.336  
...                  ...  
398643            41.094  
398644            45.902  
398645            38.918  
398646            34.951  
398647            40.949  

[398648 rows x 5 columns]

In [44]:
df.to_csv('df1.csv', index = True)

In [45]:
pd.read_csv('df1.csv')

Unnamed: 0             waktu_setempat   id_jalan  id_titik_mulai  \
0                0  2020-02-01 01:00:00+00:00  691007296        21390008   
1                1  2020-02-01 01:00:00+00:00   47010584      1677092762   
2                2  2020-02-01 01:00:00+00:00   22932408        26486694   
3                3  2020-02-01 01:00:00+00:00  142479648      1111592522   
4                4  2020-02-01 01:00:00+00:00    8504977      5940503398   
...            ...                        ...        ...             ...   
398643      398643  2020-02-22 23:00:00+00:00    3691841        18235127   
398644      398644  2020-02-22 23:00:00+00:00    3691841      1250564256   
398645      398645  2020-02-22 23:00:00+00:00  182210371        33139383   
398646      398646  2020-02-22 23:00:00+00:00    8504977      1623682036   
398647      398647  2020-02-22 23:00:00+00:00  150783571       290025573   

        id_titik_akhir  rerata_kecepatan  
0           1425033102            29.126  
1            579493410            46.576  
2           1930267566            36.587  
3           3775231113            34.063  
4           5940503394            38.336  
...                ...               ...  
398643      1590448416            41.094  
398644        18293380            45.902  
398645        33139375            38.918  
398646        26467191            34.951  
398647       873734149            40.949  

[398648 rows x 6 columns]

In [ ]:
pip install openpyxl

In [46]:
data1 = pd.read_excel('cuaca_test.xlsx')
data1.head()

Date    Tx
0 2023-01-01  31.0
1 2023-01-02  31.5
2 2023-01-03  32.8
3 2023-01-04  34.0
4 2023-01-05  34.2

In [47]:
data2 = pd.read_excel('cuaca_train.xlsx')
data2.head()

Date    Tx
0 2022-01-01  34.4
1 2022-01-02  34.3
2 2022-01-03  32.8
3 2022-01-04  33.0
4 2022-01-05  32.0

In [49]:
data_gabung = pd.concat([data2,data1], axis = 0)
data_gabung.head()


Date    Tx
0 2022-01-01  34.4
1 2022-01-02  34.3
2 2022-01-03  32.8
3 2022-01-04  33.0
4 2022-01-05  32.0

In [50]:
data_gabung

Date    Tx
0   2022-01-01  34.4
1   2022-01-02  34.3
2   2022-01-03  32.8
3   2022-01-04  33.0
4   2022-01-05  32.0
..         ...   ...
279 2023-10-07  33.8
280 2023-10-08  35.1
281 2023-10-09  35.0
282 2023-10-10  35.5
283 2023-10-11  34.8

[649 rows x 2 columns]

In [51]:
data_gabung.to_excel('data_gabung.xlsx', index = False)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=235be482-bea5-41e0-a131-c60cdaf79d4f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>