In [2]:
import numpy as np
import pandas as pd

# STACK, SPLIT, RESIZE

In [41]:
x = np.array([[1,2,3],[5,6,7]])
y = np.array([2,3,4])
z = np.array([7,8,9])
xy = np.vstack((x,y,z))
print(xy)

[[1 2 3]
 [5 6 7]
 [2 3 4]
 [7 8 9]]


In [44]:
a = np.array([[10],[11],[12],[13]])
A = np.hstack((xy,a))
A

array([[ 1,  2,  3, 10],
       [ 5,  6,  7, 11],
       [ 2,  3,  4, 12],
       [ 7,  8,  9, 13]])

In [52]:
b = np.hsplit(A, 2)
b

[array([[1, 2],
        [5, 6],
        [2, 3],
        [7, 8]]),
 array([[ 3, 10],
        [ 7, 11],
        [ 4, 12],
        [ 9, 13]])]

In [54]:
c = np.vsplit(A,2)
c

[array([[ 1,  2,  3, 10],
        [ 5,  6,  7, 11]]),
 array([[ 2,  3,  4, 12],
        [ 7,  8,  9, 13]])]

In [77]:
np.resize(A, (3,3))

array([[ 1,  2,  3],
       [10,  5,  6],
       [ 7, 11,  2]])

In [78]:
np.resize(A, (2,2))

array([[ 1,  2],
       [ 3, 10]])

# DIAGONAL

In [60]:
A

array([[ 1,  2,  3, 10],
       [ 5,  6,  7, 11],
       [ 2,  3,  4, 12],
       [ 7,  8,  9, 13]])

In [55]:
diag1 = np.diag(A)
diag1

array([ 1,  6,  4, 13])

In [58]:
np.diag(np.flip(A)) #

array([13,  4,  6,  1])

In [61]:
np.fliplr(A)

array([[10,  3,  2,  1],
       [11,  7,  6,  5],
       [12,  4,  3,  2],
       [13,  9,  8,  7]])

In [62]:
np.flip(A)

array([[13,  9,  8,  7],
       [12,  4,  3,  2],
       [11,  7,  6,  5],
       [10,  3,  2,  1]])

In [56]:
diag2 = np.diag(np.fliplr(A)) # reverse the order of array
diag2

array([10,  7,  3,  7])

## select value other than diagonal

In [65]:
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
A

array([[ 1,  2,  3, 10],
       [ 5,  6,  7, 11],
       [ 2,  3,  4, 12],
       [ 7,  8,  9, 13]])

In [71]:
rows, col = matrix.shape

In [73]:
desired_elements = []
for i in range(rows):
    for j in range(col):
        if i != j and i != (rows - 1 - j):
            desired_elements.append(matrix[i][j])

print(desired_elements)

[1, 3, 5, 7]


# MATRIX OPERATION

In [87]:
mtx1 = np.arange(1,10).reshape((3,3))
mtx1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
mtx2 = np.arange(21,30).reshape((3,3))
mtx2

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [92]:
jumlah  = mtx1 + mtx2
jumlah

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [93]:
kurang = mtx1 - mtx2;kurang

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [97]:
skalar = mtx1 * mtx2;skalar

array([[ 21,  44,  69],
       [ 96, 125, 156],
       [189, 224, 261]])

In [95]:
perkalian = mtx1 @ mtx2;perkalian

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [98]:
perkalian2 = np.dot(mtx1, mtx2);perkalian2

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [100]:
np.transpose(perkalian)

array([[150, 366, 582],
       [156, 381, 606],
       [162, 396, 630]])

In [101]:
np.transpose(A)

array([[ 1,  5,  2,  7],
       [ 2,  6,  3,  8],
       [ 3,  7,  4,  9],
       [10, 11, 12, 13]])

In [74]:
eigenvalue, eigenvector = np.linalg.eig(A)

In [75]:
eigenvalue

array([ 2.84530518e+01, -4.28917108e+00, -5.27251810e-17, -1.63880686e-01])

In [76]:
eigenvector

array([[ 3.25929620e-01,  6.17189934e-01,  4.08248290e-01,
        -7.19998633e-02],
       [ 5.27971978e-01, -2.11673977e-01, -8.16496581e-01,
        -6.40793482e-01],
       [ 4.17279297e-01,  5.99238596e-01,  4.08248290e-01,
         7.58878121e-01],
       [ 6.63998089e-01, -4.63879098e-01, -5.65626745e-16,
        -9.11248148e-02]])

In [137]:
det = np.linalg.det(A);det

7.99360577730114e-15

In [138]:
det1 = np.linalg.det(mtx1);det1

0.0

In [140]:
inv = np.linalg.inv(A);inv

array([[ 1.00079992e+15, -1.12589991e+15, -7.50599938e+14,
         8.75699928e+14],
       [-2.00159983e+15,  2.25179981e+15,  1.50119988e+15,
        -1.75139986e+15],
       [ 1.00079992e+15, -1.12589991e+15, -7.50599938e+14,
         8.75699928e+14],
       [-5.55555556e-01,  0.00000000e+00,  6.66666667e-01,
        -1.11111111e-01]])

# MAX MIN SORT MEDIAN

In [118]:
data = pd.read_excel('max_min.xlsx')
data

Country       Place  Value
0      US    New York    562
1      US    Michigan    854
2      US    Illinois    356
3      UK      London    778
4      UK  Manchester    512
5   Spain      Madrid    509
6   India      Mumbai    196
7      US      Kansas    894
8      UK   Liverpool    796
9   Spain   Barcelona    792

In [112]:
def findmax(input):
    max_value = input[0]
    for value in input:
        if value > max_value:
            max_value = value
    return max_value

In [115]:
findmax(data['Value'])

894

In [119]:
def findmin(input):
    min_value = input[0]
    for value in input:
        if value < min_value:
            min_value = value
    return min_value

In [120]:
findmin(data['Value'])

196

In [127]:
data['Value'].max()

894

In [128]:
data['Value'].min()

196

In [133]:
len(data['Value'])

10

In [134]:
def sorting(input):
    n = len(input)
    for i in range(n-1):
        for j in range(n - i - 1):
            if input[j] > input[j+1]:
                input[j], input[j+1] = input[j+1], input[j]

In [136]:
sorting(data['Value'])
data['Value']

0    196
1    356
2    509
3    512
4    562
5    778
6    792
7    796
8    854
9    894
Name: Value, dtype: int64

In [12]:
data2 = [[10, 18, 11], [13, 15, 8], [9, 20, 3]]
df = pd.DataFrame(data2)
df

0   1   2
0  10  18  11
1  13  15   8
2   9  20   3

In [13]:
df = df.set_axis(["x1","x2","x3"], axis = 1)
df

x1  x2  x3
0  10  18  11
1  13  15   8
2   9  20   3

In [14]:
df = df.set_axis(['y1','y2','y3'], axis = 0)
df

x1  x2  x3
y1  10  18  11
y2  13  15   8
y3   9  20   3

In [15]:
df.max()

x1    13
x2    20
x3    11
dtype: int64